# Generated by Django 6.0.2 on 2026-02-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
