# Generated by Django 6.0.2 on 2026-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='noise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
