# Generated by Django 6.0.2 on 2026-02-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_humidity_alert_noise_alert_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
