# Generated by Django 6.0.2 on 2026-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
