# Generated by Django 6.0.2 on 2026-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, default='Normal', max_length=20),
        ),
    ]
