# Generated by Django 6.0.2 on 2026-02-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
