# Generated by Django 6.0.2 on 2026-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='noise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
