# Generated by Django 6.0.2 on 2026-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='last_maintenance_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='vibration',
            field=models.FloatField(default=0),
        ),
    ]
