# Generated by Django 6.0.2 on 2026-02-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_device_location_device_device_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicehistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.device'),
        ),
    ]
