# Generated by Django 6.0.2 on 2026-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_rename_created_at_devicehistory_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_maintenance_at',
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
