# Generated by Django 6.0.2 on 2026-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Smart IoT Platform', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('system_mode', models.CharField(default='normal', max_length=20)),
                ('theme', models.CharField(default='auto', max_length=10)),
                ('email_notify', models.BooleanField(default=True)),
                ('sms_notify', models.BooleanField(default=False)),
                ('dashboard_notify', models.BooleanField(default=True)),
            ],
        ),
    ]
