# Generated by Django 6.0.2 on 2026-03-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0004_usersettings_delete_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='dark_mode',
            new_name='dashboard_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='system_alerts',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='system_mode',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='system_name',
            field=models.CharField(default='Monitoring Platform', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme_mode',
            field=models.CharField(default='LIGHT', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
