# Generated by Django 6.0.2 on 2026-03-02 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0005_rename_dark_mode_usersettings_dashboard_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dashboard_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_alerts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='sms_alerts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='system_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='theme_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='timezone',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
