# Generated by Django 6.0.2 on 2026-03-03 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0006_remove_usersettings_dashboard_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='notifications_enabled',
            new_name='dashboard_alerts',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='LIGHT', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
